name: monitor
apiVersion: v1
version: 2.8.12
appVersion: 1.0.11
description: Helm chart for MicroSegX monitor services
home: https://microsegx.com
icon: https://microsegx.com/icon.png
maintainers:
  - name: microsegx-team
    email: support@microsegx.com
engine: gotpl