export interface NetworkRule {
  id: number;
  comment: string;
  from: string;
  to: string;
  applications: Array<string>;
  ports: string;
  action: string;
  cfg_type: string;
  disable: boolean;
  created_timestamp: number;
  last_modified_timestamp: number;
  learned: boolean;
  priority: number;
  match_counter: number;
  last_match_timestamp: number;
  state?: string;
  remove?: boolean;
  selected?: boolean;
  rule_source?: string;
  legacy_preview?: boolean;
  auto_policy_class?: string;
  auto_policy_confidence?: number;
  auto_policy_active?: boolean;
  auto_policy_last_observed_timestamp?: number;
  auto_policy_expires_timestamp?: number;
  auto_policy_periodic_slots?: number[];
  auto_policy_reason_codes?: string[];
}
