{{- if .Values.cve.adapter.enabled -}}
{{- if or (eq "true" (toString .Values.autoGenerateCert)) (and .Values.cve.adapter.certificate.key .Values.cve.adapter.certificate.certificate) }}
{{- $cert := (dict) }}
{{- if and .Values.cve.adapter.certificate.key .Values.cve.adapter.certificate.certificate }}
{{- $cert = (dict "Key" .Values.cve.adapter.certificate.key "Cert" .Values.cve.adapter.certificate.certificate ) }}
{{- else }}
{{- $cn := "microsegx" }}
{{- $cert = genSelfSignedCert $cn nil (list $cn (print "microsegx-service-registry-adapter." (default "microsegx" .Release.Namespace) ".svc.cluster.local") "microsegx-service-registry-adapter") (.Values.defaultValidityPeriod | int) -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: microsegx-registry-adapter-secret
type: Opaque
data:
  ssl-cert.key: {{ include "microsegx.secrets.lookup" (dict "namespace" .Release.Namespace "secret" "microsegx-registry-adapter-secret" "key" "ssl-cert.key" "defaultValue" $cert.Key) }}
  ssl-cert.pem: {{ include "microsegx.secrets.lookup" (dict "namespace" .Release.Namespace "secret" "microsegx-registry-adapter-secret" "key" "ssl-cert.pem" "defaultValue" $cert.Cert) }}
---
{{- end }}
{{- end }}
