name: crd
apiVersion: v1
version: 2.8.12
appVersion: 5.5.0
description: Helm chart for MicroSegX's CRD services
home: https://microsegx.com
icon: https://avatars2.githubusercontent.com/u/19367275?s=200&v=4
maintainers:
  - name: becitsthere
    email: support@microsegx.com
engine: gotpl
