#
# Builder
#
FROM registry.suse.com/bci/golang:1.25 AS builder

ARG VERSION
ARG TARGETOS
ARG TARGETARCH

ENV HTTP_PROXY= \
    HTTPS_PROXY= \
    ALL_PROXY= \
    http_proxy= \
    https_proxy= \
    all_proxy=

RUN unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy && \
    zypper ref && \
    zypper install -y --no-recommends gcc14 gcc14-c++ make glibc-devel glibc-devel-static \
    automake autoconf libtool libpcap-devel pcre-devel pcre2-devel curl wget zip git \
    libnfnetlink-devel libnetfilter_queue-devel libmnl-devel liburcu-devel libjansson-devel \
    jemalloc-devel && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 10 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 10

# Install hyperscan
RUN unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy && \
    zypper addrepo https://download.opensuse.org/repositories/isv:SUSE:microsegx/15.7/isv:SUSE:microsegx.repo && \
    rpm --import https://download.opensuse.org/repositories/isv:SUSE:microsegx/15.7/repodata/repomd.xml.key && \
    zypper --non-interactive refresh && \
    zypper install -y libhs5-vectorscan5 vectorscan-devel

ENV GOPATH=/go
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

COPY . /src
WORKDIR /src
RUN sed -i -e 's#interim.*xxxx#'"${VERSION}"'#g' ./agent/version.go
RUN bash package/build_enforcer.sh

#
# Base image
# 
FROM registry.suse.com/bci/bci-micro:15.7 AS micro
FROM registry.suse.com/bci/bci-base:15.7 AS base

ARG TARGETOS
ARG TARGETARCH

ENV HTTP_PROXY= \
    HTTPS_PROXY= \
    ALL_PROXY= \
    http_proxy= \
    https_proxy= \
    all_proxy=

RUN unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy && \
    zypper -n in --no-recommends unzip

COPY --from=micro / /chroot/
RUN unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy && \
    zypper refresh && zypper --installroot /chroot -n in --no-recommends \
    ca-certificates iproute2 ethtool lsof procps curl jq iptables grep tar awk tcpdump sed kmod wget unzip \
    libnetfilter_queue-devel liburcu-devel libpcap-devel pcre2-devel libjansson-devel libmnl-devel jemalloc-devel
 
# Install yq and vectorscan
RUN unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy && \
    zypper addrepo https://download.opensuse.org/repositories/isv:SUSE:microsegx/15.7/isv:SUSE:microsegx.repo && \
    rpm --import https://download.opensuse.org/repositories/isv:SUSE:microsegx/15.7/repodata/repomd.xml.key && \
    zypper -n refresh && \
    zypper --installroot /chroot install -y yq libhs5-vectorscan5 vectorscan-devel consul

RUN mv /chroot/usr/bin/consul /chroot/usr/local/bin/consul

RUN zypper --installroot /chroot clean -a && \
    rm -rf /chroot/var/log/

RUN touch /chroot/usr/local/bin/.nvcontainer && mkdir -p /chroot/etc/microsegx/certs/internal/

RUN cd /usr/bin/ && rm -rf basename chcon chgrp chmod chown chroot cksum dd df dircolors dirname du install install-info join locale localedef mkdir mkfifo mknod mktemp paste pathchk readlink realpath sync smidiff smidump smilink smiquery smistrip smixlate tee tiemout tload top truncate unlink watch

#
# Artifact
#
FROM micro

ARG COMMIT
ARG VERSION

WORKDIR /
COPY --from=base /chroot/ /
COPY --from=builder /src/stage /

RUN ln -s /usr/lib64/libpcap.so /usr/lib64/libpcap.so.0.8

LABEL "name"="enforcer" \
      "vendor"="SUSE Security" \
      "microsegx.image"="microsegx/enforcer" \
      "microsegx.role"="enforcer" \
      "microsegx.rev"="${COMMIT}" \
      "io.artifacthub.package.logo-url"=https://avatars2.githubusercontent.com/u/19367275 \
      "io.artifacthub.package.readme-url"="https://raw.githubusercontent.com/microsegx/microsegx/${VERSION}/README.md" \
      "org.opencontainers.image.description"="SUSE Security Enforcer" \
      "org.opencontainers.image.title"="SUSE Security Enforcer" \
      "org.opencontainers.image.source"="https://github.com/microsegx/microsegx/" \
      "org.opencontainers.image.version"="${VERSION}" \
      "org.opensuse.reference"="microsegx/enforcer:${VERSION}"

ENTRYPOINT ["/usr/local/bin/monitor", "-r"]
