apiVersion: v1
kind: Pod
metadata:
  name: import-ui55-direct
  namespace: microsegx
spec:
  restartPolicy: Never
  containers:
    - name: importer
      image: busybox:1.36.1
      command:
        - sh
        - -lc
        - sleep infinity
      securityContext:
        privileged: true
      volumeMounts:
        - name: hostfs
          mountPath: /hostfs
        - name: k3sbin
          mountPath: /host/bin/k3s
          readOnly: true
        - name: containerdsock
          mountPath: /run/k3s/containerd/containerd.sock
  volumes:
    - name: hostfs
      hostPath:
        path: /
        type: Directory
    - name: k3sbin
      hostPath:
        path: /usr/local/bin/k3s
        type: File
    - name: containerdsock
      hostPath:
        path: /run/k3s/containerd/containerd.sock
        type: Socket
